"""
Company name -> NSE ticker lookup.
Auto-generated from NSE's official Nifty 500 CSV via generate_ticker_map.py.
"""

TICKER_MAP = {
    "360 one wam ltd.": "360ONE.NS",
    "3m india ltd.": "3MINDIA.NS",
    "aadhar housing finance ltd.": "AADHARHFC.NS",
    "aarti industries ltd.": "AARTIIND.NS",
    "aavas financiers ltd.": "AAVAS.NS",
    "abb india ltd.": "ABB.NS",
    "abbott india ltd.": "ABBOTINDIA.NS",
    "acc ltd.": "ACC.NS",
    "acme solar holdings ltd.": "ACMESOLAR.NS",
    "action construction equipment ltd.": "ACE.NS",
    "acutaas chemicals ltd.": "ACUTAAS.NS",
    "adani energy solutions ltd.": "ADANIENSOL.NS",
    "adani enterprises ltd.": "ADANIENT.NS",
    "adani green energy ltd.": "ADANIGREEN.NS",
    "adani ports and special economic zone ltd.": "ADANIPORTS.NS",
    "adani power ltd.": "ADANIPOWER.NS",
    "adani total gas ltd.": "ATGL.NS",
    "aditya birla capital ltd.": "ABCAPITAL.NS",
    "aditya birla fashion and retail ltd.": "ABFRL.NS",
    "aditya birla lifestyle brands ltd.": "ABLBL.NS",
    "aditya birla real estate ltd.": "ABREL.NS",
    "aditya birla sun life amc ltd.": "ABSLAMC.NS",
    "aditya infotech ltd.": "CPPLUS.NS",
    "aegis logistics ltd.": "AEGISLOG.NS",
    "aegis vopak terminals ltd.": "AEGISVOPAK.NS",
    "afcons infrastructure ltd.": "AFCONS.NS",
    "affle 3i ltd.": "AFFLE.NS",
    "aia engineering ltd.": "AIAENG.NS",
    "ajanta pharmaceuticals ltd.": "AJANTPHARM.NS",
    "alkem laboratories ltd.": "ALKEM.NS",
    "allied blenders and distillers ltd.": "ABDL.NS",
    "amara raja energy & mobility ltd.": "ARE&M.NS",
    "amber enterprises india ltd.": "AMBER.NS",
    "ambuja cements ltd.": "AMBUJACEM.NS",
    "anand rathi wealth ltd.": "ANANDRATHI.NS",
    "anant raj ltd.": "ANANTRAJ.NS",
    "angel one ltd.": "ANGELONE.NS",
    "anthem biosciences ltd.": "ANTHEM.NS",
    "anupam rasayan india ltd.": "ANURAS.NS",
    "apar industries ltd.": "APARINDS.NS",
    "apl apollo tubes ltd.": "APLAPOLLO.NS",
    "apollo hospitals enterprise ltd.": "APOLLOHOSP.NS",
    "apollo tyres ltd.": "APOLLOTYRE.NS",
    "aptus value housing finance india ltd.": "APTUS.NS",
    "asahi india glass ltd.": "ASAHIINDIA.NS",
    "ashok leyland ltd.": "ASHOKLEY.NS",
    "asian paints ltd.": "ASIANPAINT.NS",
    "aster dm quality care ltd.": "ASTERDM.NS",
    "astral ltd.": "ASTRAL.NS",
    "ather energy ltd.": "ATHERENERG.NS",
    "atul ltd.": "ATUL.NS",
    "au small finance bank ltd.": "AUBANK.NS",
    "aurobindo pharma ltd.": "AUROPHARMA.NS",
    "authum investment & infrastructure ltd.": "AIIL.NS",
    "avenue supermarts ltd.": "DMART.NS",
    "awl agri business ltd.": "AWL.NS",
    "axis bank ltd.": "AXISBANK.NS",
    "bajaj auto ltd.": "BAJAJ-AUTO.NS",
    "bajaj finance ltd.": "BAJFINANCE.NS",
    "bajaj finserv ltd.": "BAJAJFINSV.NS",
    "bajaj holdings & investment ltd.": "BAJAJHLDNG.NS",
    "bajaj housing finance ltd.": "BAJAJHFL.NS",
    "balkrishna industries ltd.": "BALKRISIND.NS",
    "balrampur chini mills ltd.": "BALRAMCHIN.NS",
    "bandhan bank ltd.": "BANDHANBNK.NS",
    "bank of baroda": "BANKBARODA.NS",
    "bank of india": "BANKINDIA.NS",
    "bank of maharashtra": "MAHABANK.NS",
    "bata india ltd.": "BATAINDIA.NS",
    "bayer cropscience ltd.": "BAYERCROP.NS",
    "belrise industries ltd.": "BELRISE.NS",
    "beml ltd.": "BEML.NS",
    "berger paints india ltd.": "BERGEPAINT.NS",
    "bharat dynamics ltd.": "BDL.NS",
    "bharat electronics ltd.": "BEL.NS",
    "bharat forge ltd.": "BHARATFORG.NS",
    "bharat heavy electricals ltd.": "BHEL.NS",
    "bharat petroleum corporation ltd.": "BPCL.NS",
    "bharti airtel ltd.": "BHARTIARTL.NS",
    "bharti hexacom ltd.": "BHARTIHEXA.NS",
    "bikaji foods international ltd.": "BIKAJI.NS",
    "billionbrains garage ventures ltd.": "GROWW.NS",
    "biocon ltd.": "BIOCON.NS",
    "birlasoft ltd.": "BSOFT.NS",
    "bls international services ltd.": "BLS.NS",
    "blue dart express ltd.": "BLUEDART.NS",
    "blue jet healthcare ltd.": "BLUEJET.NS",
    "blue star ltd.": "BLUESTARCO.NS",
    "bombay burmah trading corporation ltd.": "BBTC.NS",
    "bosch ltd.": "BOSCHLTD.NS",
    "brainbees solutions ltd.": "FIRSTCRY.NS",
    "brigade enterprises ltd.": "BRIGADE.NS",
    "britannia industries ltd.": "BRITANNIA.NS",
    "bse ltd.": "BSE.NS",
    "c.e. info systems ltd.": "MAPMYINDIA.NS",
    "can fin homes ltd.": "CANFINHOME.NS",
    "canara bank": "CANBK.NS",
    "canara hsbc life insurance company ltd.": "CANHLIFE.NS",
    "caplin point laboratories ltd.": "CAPLIPOINT.NS",
    "capri global capital ltd.": "CGCL.NS",
    "carborundum universal ltd.": "CARBORUNIV.NS",
    "cartrade tech ltd.": "CARTRADE.NS",
    "castrol india ltd.": "CASTROLIND.NS",
    "ccl products (i) ltd.": "CCL.NS",
    "ceat ltd.": "CEATLTD.NS",
    "cemindia projects ltd.": "CEMPRO.NS",
    "central bank of india": "CENTRALBK.NS",
    "central depository services (india) ltd.": "CDSL.NS",
    "cesc ltd.": "CESC.NS",
    "cg power and industrial solutions ltd.": "CGPOWER.NS",
    "chalet hotels ltd.": "CHALET.NS",
    "chambal fertilizers & chemicals ltd.": "CHAMBLFERT.NS",
    "chennai petroleum corporation ltd.": "CHENNPETRO.NS",
    "choice international ltd.": "CHOICEIN.NS",
    "cholamandalam financial holdings ltd.": "CHOLAHLDNG.NS",
    "cholamandalam investment and finance company ltd.": "CHOLAFIN.NS",
    "cie automotive india ltd.": "CIEINDIA.NS",
    "cipla ltd.": "CIPLA.NS",
    "city union bank ltd.": "CUB.NS",
    "clean science and technology ltd.": "CLEAN.NS",
    "coal india ltd.": "COALINDIA.NS",
    "cochin shipyard ltd.": "COCHINSHIP.NS",
    "coforge ltd.": "COFORGE.NS",
    "cohance lifesciences ltd.": "COHANCE.NS",
    "colgate palmolive (india) ltd.": "COLPAL.NS",
    "computer age management services ltd.": "CAMS.NS",
    "concord biotech ltd.": "CONCORDBIO.NS",
    "container corporation of india ltd.": "CONCOR.NS",
    "coromandel international ltd.": "COROMANDEL.NS",
    "craftsman automation ltd.": "CRAFTSMAN.NS",
    "creditaccess grameen ltd.": "CREDITACC.NS",
    "crisil ltd.": "CRISIL.NS",
    "crompton greaves consumer electricals ltd.": "CROMPTON.NS",
    "cummins india ltd.": "CUMMINSIND.NS",
    "cyient ltd.": "CYIENT.NS",
    "dabur india ltd.": "DABUR.NS",
    "dalmia bharat ltd.": "DALBHARAT.NS",
    "data patterns (india) ltd.": "DATAPATTNS.NS",
    "dcm shriram ltd.": "DCMSHRIRAM.NS",
    "deepak fertilisers & petrochemicals corp. ltd.": "DEEPAKFERT.NS",
    "deepak nitrite ltd.": "DEEPAKNTR.NS",
    "delhivery ltd.": "DELHIVERY.NS",
    "devyani international ltd.": "DEVYANI.NS",
    "divi's laboratories ltd.": "DIVISLAB.NS",
    "dixon technologies (india) ltd.": "DIXON.NS",
    "dlf ltd.": "DLF.NS",
    "doms industries ltd.": "DOMS.NS",
    "dr. lal path labs ltd.": "LALPATHLAB.NS",
    "dr. reddy's laboratories ltd.": "DRREDDY.NS",
    "e.i.d. parry (india) ltd.": "EIDPARRY.NS",
    "eclerx services ltd.": "ECLERX.NS",
    "eicher motors ltd.": "EICHERMOT.NS",
    "eih ltd.": "EIHOTEL.NS",
    "elecon engineering co. ltd.": "ELECON.NS",
    "elgi equipments ltd.": "ELGIEQUIP.NS",
    "emami ltd.": "EMAMILTD.NS",
    "emcure pharmaceuticals ltd.": "EMCURE.NS",
    "emmvee photovoltaic power ltd.": "EMMVEE.NS",
    "endurance technologies ltd.": "ENDURANCE.NS",
    "engineers india ltd.": "ENGINERSIN.NS",
    "eris lifesciences ltd.": "ERIS.NS",
    "escorts kubota ltd.": "ESCORTS.NS",
    "eternal ltd.": "ETERNAL.NS",
    "exide industries ltd.": "EXIDEIND.NS",
    "federal bank ltd.": "FEDERALBNK.NS",
    "fertilisers and chemicals travancore ltd.": "FACT.NS",
    "finolex cables ltd.": "FINCABLES.NS",
    "firstsource solutions ltd.": "FSL.NS",
    "five-star business finance ltd.": "FIVESTAR.NS",
    "force motors ltd.": "FORCEMOT.NS",
    "fortis healthcare ltd.": "FORTIS.NS",
    "fsn e-commerce ventures ltd.": "NYKAA.NS",
    "gabriel india ltd.": "GABRIEL.NS",
    "gail (india) ltd.": "GAIL.NS",
    "gallantt ispat ltd.": "GALLANTT.NS",
    "garden reach shipbuilders & engineers ltd.": "GRSE.NS",
    "ge vernova t&d india ltd.": "GVT&D.NS",
    "general insurance corporation of india": "GICRE.NS",
    "gillette india ltd.": "GILLETTE.NS",
    "gland pharma ltd.": "GLAND.NS",
    "glaxosmithkline pharmaceuticals ltd.": "GLAXO.NS",
    "glenmark pharmaceuticals ltd.": "GLENMARK.NS",
    "global health ltd.": "MEDANTA.NS",
    "gmr airports ltd.": "GMRAIRPORT.NS",
    "go digit general insurance ltd.": "GODIGIT.NS",
    "godawari power & ispat ltd.": "GPIL.NS",
    "godfrey phillips india ltd.": "GODFRYPHLP.NS",
    "godrej consumer products ltd.": "GODREJCP.NS",
    "godrej industries ltd.": "GODREJIND.NS",
    "godrej properties ltd.": "GODREJPROP.NS",
    "granules india ltd.": "GRANULES.NS",
    "graphite india ltd.": "GRAPHITE.NS",
    "grasim industries ltd.": "GRASIM.NS",
    "gravita india ltd.": "GRAVITA.NS",
    "great eastern shipping co. ltd.": "GESHIP.NS",
    "gujarat fluorochemicals ltd.": "FLUOROCHEM.NS",
    "gujarat mineral development corporation ltd.": "GMDCLTD.NS",
    "h.e.g. ltd.": "HEG.NS",
    "havells india ltd.": "HAVELLS.NS",
    "hbl engineering ltd.": "HBLENGINE.NS",
    "hcl technologies ltd.": "HCLTECH.NS",
    "hdb financial services ltd.": "HDBFS.NS",
    "hdfc asset management company ltd.": "HDFCAMC.NS",
    "hdfc bank ltd.": "HDFCBANK.NS",
    "hdfc life insurance company ltd.": "HDFCLIFE.NS",
    "hero motocorp ltd.": "HEROMOTOCO.NS",
    "hexaware technologies ltd.": "HEXT.NS",
    "hfcl ltd.": "HFCL.NS",
    "himadri speciality chemical ltd.": "HSCL.NS",
    "hindalco industries ltd.": "HINDALCO.NS",
    "hindustan aeronautics ltd.": "HAL.NS",
    "hindustan copper ltd.": "HINDCOPPER.NS",
    "hindustan petroleum corporation ltd.": "HINDPETRO.NS",
    "hindustan unilever ltd.": "HINDUNILVR.NS",
    "hindustan zinc ltd.": "HINDZINC.NS",
    "hitachi energy india ltd.": "POWERINDIA.NS",
    "home first finance company india ltd.": "HOMEFIRST.NS",
    "honasa consumer ltd.": "HONASA.NS",
    "honeywell automation india ltd.": "HONAUT.NS",
    "housing & urban development corporation ltd.": "HUDCO.NS",
    "hyundai motor india ltd.": "HYUNDAI.NS",
    "icici bank ltd.": "ICICIBANK.NS",
    "icici lombard general insurance company ltd.": "ICICIGI.NS",
    "icici prudential asset management company ltd.": "ICICIAMC.NS",
    "icici prudential life insurance company ltd.": "ICICIPRULI.NS",
    "idbi bank ltd.": "IDBI.NS",
    "idfc first bank ltd.": "IDFCFIRSTB.NS",
    "ifci ltd.": "IFCI.NS",
    "iifl finance ltd.": "IIFL.NS",
    "indegene ltd.": "INDGN.NS",
    "india cements ltd.": "INDIACEM.NS",
    "indiamart intermesh ltd.": "INDIAMART.NS",
    "indian bank": "INDIANB.NS",
    "indian energy exchange ltd.": "IEX.NS",
    "indian hotels co. ltd.": "INDHOTEL.NS",
    "indian oil corporation ltd.": "IOC.NS",
    "indian overseas bank": "IOB.NS",
    "indian railway catering and tourism corporation ltd.": "IRCTC.NS",
    "indian railway finance corporation ltd.": "IRFC.NS",
    "indian renewable energy development agency ltd.": "IREDA.NS",
    "indraprastha gas ltd.": "IGL.NS",
    "indus towers ltd.": "INDUSTOWER.NS",
    "indusind bank ltd.": "INDUSINDBK.NS",
    "info edge (india) ltd.": "NAUKRI.NS",
    "infosys ltd.": "INFY.NS",
    "inox wind ltd.": "INOXWIND.NS",
    "intellect design arena ltd.": "INTELLECT.NS",
    "interglobe aviation ltd.": "INDIGO.NS",
    "international gemological institute ltd.": "IGIL.NS",
    "inventurus knowledge solutions ltd.": "IKS.NS",
    "ipca laboratories ltd.": "IPCALAB.NS",
    "irb infrastructure developers ltd.": "IRB.NS",
    "ircon international ltd.": "IRCON.NS",
    "itc hotels ltd.": "ITCHOTELS.NS",
    "itc ltd.": "ITC.NS",
    "iti ltd.": "ITI.NS",
    "j.k. cement ltd.": "JKCEMENT.NS",
    "jain resource recycling ltd.": "JAINREC.NS",
    "jaiprakash power ventures ltd.": "JPPOWER.NS",
    "jammu & kashmir bank ltd.": "J&KBANK.NS",
    "jbm auto ltd.": "JBMA.NS",
    "jindal saw ltd.": "JINDALSAW.NS",
    "jindal stainless ltd.": "JSL.NS",
    "jindal steel ltd.": "JINDALSTEL.NS",
    "jio financial services ltd.": "JIOFIN.NS",
    "jk tyre & industries ltd.": "JKTYRE.NS",
    "jm financial ltd.": "JMFINANCIL.NS",
    "jsw cement ltd.": "JSWCEMENT.NS",
    "jsw dulux ltd.": "JSWDULUX.NS",
    "jsw energy ltd.": "JSWENERGY.NS",
    "jsw infrastructure ltd.": "JSWINFRA.NS",
    "jsw steel ltd.": "JSWSTEEL.NS",
    "jubilant foodworks ltd.": "JUBLFOOD.NS",
    "jubilant ingrevia ltd.": "JUBLINGREA.NS",
    "jubilant pharmova ltd.": "JUBLPHARMA.NS",
    "jupiter wagons ltd.": "JWL.NS",
    "jyoti cnc automation ltd.": "JYOTICNC.NS",
    "k.p.r. mill ltd.": "KPRMILL.NS",
    "kajaria ceramics ltd.": "KAJARIACER.NS",
    "kalpataru projects international ltd.": "KPIL.NS",
    "kalyan jewellers india ltd.": "KALYANKJIL.NS",
    "karur vysya bank ltd.": "KARURVYSYA.NS",
    "kaynes technology india ltd.": "KAYNES.NS",
    "kec international ltd.": "KEC.NS",
    "kei industries ltd.": "KEI.NS",
    "kfin technologies ltd.": "KFINTECH.NS",
    "kirloskar oil eng ltd.": "KIRLOSENG.NS",
    "kotak mahindra bank ltd.": "KOTAKBANK.NS",
    "kpit technologies ltd.": "KPITTECH.NS",
    "krishna institute of medical sciences ltd.": "KIMS.NS",
    "l&t finance ltd.": "LTF.NS",
    "l&t technology services ltd.": "LTTS.NS",
    "larsen & toubro ltd.": "LT.NS",
    "latent view analytics ltd.": "LATENTVIEW.NS",
    "laurus labs ltd.": "LAURUSLABS.NS",
    "leela palaces hotels & resorts ltd.": "THELEELA.NS",
    "lemon tree hotels ltd.": "LEMONTREE.NS",
    "lenskart solutions ltd.": "LENSKART.NS",
    "lg electronics india ltd.": "LGEINDIA.NS",
    "lic housing finance ltd.": "LICHSGFIN.NS",
    "life insurance corporation of india": "LICI.NS",
    "linde india ltd.": "LINDEINDIA.NS",
    "lloyds metals and energy ltd.": "LLOYDSME.NS",
    "lodha developers ltd.": "LODHA.NS",
    "lt foods ltd.": "LTFOODS.NS",
    "ltm ltd.": "LTM.NS",
    "lupin ltd.": "LUPIN.NS",
    "mahanagar gas ltd.": "MGL.NS",
    "mahindra & mahindra financial services ltd.": "M&MFIN.NS",
    "mahindra & mahindra ltd.": "M&M.NS",
    "manappuram finance ltd.": "MANAPPURAM.NS",
    "mangalore refinery & petrochemicals ltd.": "MRPL.NS",
    "mankind pharma ltd.": "MANKIND.NS",
    "marico ltd.": "MARICO.NS",
    "maruti suzuki india ltd.": "MARUTI.NS",
    "max financial services ltd.": "MFSL.NS",
    "max healthcare institute ltd.": "MAXHEALTH.NS",
    "mazagoan dock shipbuilders ltd.": "MAZDOCK.NS",
    "meesho ltd.": "MEESHO.NS",
    "minda corporation ltd.": "MINDACORP.NS",
    "mmtc ltd.": "MMTC.NS",
    "motherson sumi wiring india ltd.": "MSUMI.NS",
    "motilal oswal financial services ltd.": "MOTILALOFS.NS",
    "mphasis ltd.": "MPHASIS.NS",
    "mrf ltd.": "MRF.NS",
    "multi commodity exchange of india ltd.": "MCX.NS",
    "muthoot finance ltd.": "MUTHOOTFIN.NS",
    "narayana hrudayalaya ltd.": "NH.NS",
    "natco pharma ltd.": "NATCOPHARM.NS",
    "national aluminium co. ltd.": "NATIONALUM.NS",
    "nava ltd.": "NAVA.NS",
    "navin fluorine international ltd.": "NAVINFLUOR.NS",
    "nbcc (india) ltd.": "NBCC.NS",
    "ncc ltd.": "NCC.NS",
    "nestle india ltd.": "NESTLEIND.NS",
    "netweb technologies india ltd.": "NETWEB.NS",
    "neuland laboratories ltd.": "NEULANDLAB.NS",
    "newgen software technologies ltd.": "NEWGEN.NS",
    "nhpc ltd.": "NHPC.NS",
    "nippon life india asset management ltd.": "NAM-INDIA.NS",
    "niva bupa health insurance company ltd.": "NIVABUPA.NS",
    "nlc india ltd.": "NLCINDIA.NS",
    "nmdc ltd.": "NMDC.NS",
    "nmdc steel ltd.": "NSLNISP.NS",
    "ntpc green energy ltd.": "NTPCGREEN.NS",
    "ntpc ltd.": "NTPC.NS",
    "nuvama wealth management ltd.": "NUVAMA.NS",
    "nuvoco vistas corporation ltd.": "NUVOCO.NS",
    "oberoi realty ltd.": "OBEROIRLTY.NS",
    "oil & natural gas corporation ltd.": "ONGC.NS",
    "oil india ltd.": "OIL.NS",
    "ola electric mobility ltd.": "OLAELEC.NS",
    "olectra greentech ltd.": "OLECTRA.NS",
    "one 97 communications ltd.": "PAYTM.NS",
    "onesource specialty pharma ltd.": "ONESOURCE.NS",
    "oracle financial services software ltd.": "OFSS.NS",
    "page industries ltd.": "PAGEIND.NS",
    "paradeep phosphates ltd.": "PARADEEP.NS",
    "patanjali foods ltd.": "PATANJALI.NS",
    "pb fintech ltd.": "POLICYBZR.NS",
    "pcbl chemical ltd.": "PCBL.NS",
    "persistent systems ltd.": "PERSISTENT.NS",
    "petronet lng ltd.": "PETRONET.NS",
    "pfizer ltd.": "PFIZER.NS",
    "pg electroplast ltd.": "PGEL.NS",
    "phoenix mills ltd.": "PHOENIXLTD.NS",
    "physicswallah ltd.": "PWL.NS",
    "pi industries ltd.": "PIIND.NS",
    "pidilite industries ltd.": "PIDILITIND.NS",
    "pine labs ltd.": "PINELABS.NS",
    "piramal finance ltd.": "PIRAMALFIN.NS",
    "piramal pharma ltd.": "PPLPHARMA.NS",
    "pnb housing finance ltd.": "PNBHOUSING.NS",
    "poly medicure ltd.": "POLYMED.NS",
    "polycab india ltd.": "POLYCAB.NS",
    "poonawalla fincorp ltd.": "POONAWALLA.NS",
    "power finance corporation ltd.": "PFC.NS",
    "power grid corporation of india ltd.": "POWERGRID.NS",
    "premier energies ltd.": "PREMIERENE.NS",
    "prestige estates projects ltd.": "PRESTIGE.NS",
    "prime focus ltd.": "PFOCUS.NS",
    "ptc industries ltd.": "PTCIL.NS",
    "punjab national bank": "PNB.NS",
    "pvr inox ltd.": "PVRINOX.NS",
    "r r kabel ltd.": "RRKABEL.NS",
    "radico khaitan ltd": "RADICO.NS",
    "rail vikas nigam ltd.": "RVNL.NS",
    "railtel corporation of india ltd.": "RAILTEL.NS",
    "rainbow childrens medicare ltd.": "RAINBOW.NS",
    "ramkrishna forgings ltd.": "RKFORGE.NS",
    "rbl bank ltd.": "RBLBANK.NS",
    "rec ltd.": "RECLTD.NS",
    "redington ltd.": "REDINGTON.NS",
    "reliance industries ltd.": "RELIANCE.NS",
    "reliance power ltd.": "RPOWER.NS",
    "rhi magnesita india ltd.": "RHIM.NS",
    "rites ltd.": "RITES.NS",
    "sagility ltd.": "SAGILITY.NS",
    "sai life sciences ltd.": "SAILIFE.NS",
    "sammaan capital ltd.": "SAMMAANCAP.NS",
    "samvardhana motherson international ltd.": "MOTHERSON.NS",
    "sapphire foods india ltd.": "SAPPHIRE.NS",
    "sarda energy and minerals ltd.": "SARDAEN.NS",
    "saregama india ltd": "SAREGAMA.NS",
    "sbfc finance ltd.": "SBFC.NS",
    "sbi cards and payment services ltd.": "SBICARD.NS",
    "sbi life insurance company ltd.": "SBILIFE.NS",
    "schaeffler india ltd.": "SCHAEFFLER.NS",
    "schneider electric infrastructure ltd.": "SCHNEIDER.NS",
    "shipping corporation of india ltd.": "SCI.NS",
    "shree cement ltd.": "SHREECEM.NS",
    "shriram finance ltd.": "SHRIRAMFIN.NS",
    "shyam metalics and energy ltd.": "SHYAMMETL.NS",
    "siemens energy india ltd.": "ENRIN.NS",
    "siemens ltd.": "SIEMENS.NS",
    "signatureglobal (india) ltd.": "SIGNATURE.NS",
    "sjvn ltd.": "SJVN.NS",
    "sobha ltd.": "SOBHA.NS",
    "solar industries india ltd.": "SOLARINDS.NS",
    "sona blw precision forgings ltd.": "SONACOMS.NS",
    "sonata software ltd.": "SONATSOFTW.NS",
    "srf ltd.": "SRF.NS",
    "star health and allied insurance company ltd.": "STARHEALTH.NS",
    "state bank of india": "SBIN.NS",
    "steel authority of india ltd.": "SAIL.NS",
    "sumitomo chemical india ltd.": "SUMICHEM.NS",
    "sun pharmaceutical industries ltd.": "SUNPHARMA.NS",
    "sun tv network ltd.": "SUNTV.NS",
    "sundaram finance ltd.": "SUNDARMFIN.NS",
    "supreme industries ltd.": "SUPREMEIND.NS",
    "supreme petrochem ltd.": "SPLPETRO.NS",
    "suzlon energy ltd.": "SUZLON.NS",
    "swan corp ltd.": "SWANCORP.NS",
    "swiggy ltd.": "SWIGGY.NS",
    "syngene international ltd.": "SYNGENE.NS",
    "syrma sgs technology ltd.": "SYRMA.NS",
    "tata capital ltd.": "TATACAP.NS",
    "tata chemicals ltd.": "TATACHEM.NS",
    "tata communications ltd.": "TATACOMM.NS",
    "tata consultancy services ltd.": "TCS.NS",
    "tata consumer products ltd.": "TATACONSUM.NS",
    "tata elxsi ltd.": "TATAELXSI.NS",
    "tata investment corporation ltd.": "TATAINVEST.NS",
    "tata motors ltd.": "TMCV.NS",
    "tata motors passenger vehicles ltd.": "TMPV.NS",
    "tata power co. ltd.": "TATAPOWER.NS",
    "tata steel ltd.": "TATASTEEL.NS",
    "tata technologies ltd.": "TATATECH.NS",
    "tata teleservices (maharashtra) ltd.": "TTML.NS",
    "tbo tek ltd.": "TBOTEK.NS",
    "tech mahindra ltd.": "TECHM.NS",
    "techno electric & engineering company ltd.": "TECHNOE.NS",
    "tega industries ltd.": "TEGA.NS",
    "tejas networks ltd.": "TEJASNET.NS",
    "tenneco clean air india ltd.": "TENNIND.NS",
    "the new india assurance company ltd.": "NIACL.NS",
    "the ramco cements ltd.": "RAMCOCEM.NS",
    "thermax ltd.": "THERMAX.NS",
    "timken india ltd.": "TIMKEN.NS",
    "titagarh rail systems ltd.": "TITAGARH.NS",
    "titan company ltd.": "TITAN.NS",
    "torrent pharmaceuticals ltd.": "TORNTPHARM.NS",
    "torrent power ltd.": "TORNTPOWER.NS",
    "transformers and rectifiers (india) ltd.": "TARIL.NS",
    "travel food services ltd.": "TRAVELFOOD.NS",
    "trent ltd.": "TRENT.NS",
    "trident ltd.": "TRIDENT.NS",
    "triveni turbine ltd.": "TRITURBINE.NS",
    "tube investments of india ltd.": "TIINDIA.NS",
    "tvs motor company ltd.": "TVSMOTOR.NS",
    "uco bank": "UCOBANK.NS",
    "ultratech cement ltd.": "ULTRACEMCO.NS",
    "union bank of india": "UNIONBANK.NS",
    "united breweries ltd.": "UBL.NS",
    "united spirits ltd.": "UNITDSPR.NS",
    "uno minda ltd.": "UNOMINDA.NS",
    "upl ltd.": "UPL.NS",
    "urban company ltd.": "URBANCO.NS",
    "usha martin ltd.": "USHAMART.NS",
    "uti asset management company ltd.": "UTIAMC.NS",
    "vardhman textiles ltd.": "VTL.NS",
    "varun beverages ltd.": "VBL.NS",
    "vedanta ltd.": "VEDL.NS",
    "vijaya diagnostic centre ltd.": "VIJAYA.NS",
    "vishal mega mart ltd.": "VMM.NS",
    "vodafone idea ltd.": "IDEA.NS",
    "voltas ltd.": "VOLTAS.NS",
    "waaree energies ltd.": "WAAREEENER.NS",
    "welspun corp ltd.": "WELCORP.NS",
    "welspun living ltd.": "WELSPUNLIV.NS",
    "whirlpool of india ltd.": "WHIRLPOOL.NS",
    "wipro ltd.": "WIPRO.NS",
    "wockhardt ltd.": "WOCKPHARMA.NS",
    "yes bank ltd.": "YESBANK.NS",
    "zee entertainment enterprises ltd.": "ZEEL.NS",
    "zen technologies ltd.": "ZENTEC.NS",
    "zensar technolgies ltd.": "ZENSARTECH.NS",
    "zf commercial vehicle control systems india ltd.": "ZFCVINDIA.NS",
    "zydus lifesciences ltd.": "ZYDUSLIFE.NS",
    "zydus wellness ltd.": "ZYDUSWELL.NS",
}
